### ISSUE TITLE
Feature request: add optional promise chain length limitation 

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird#918] opened 2015-12-15 19:04 UTC
Such feature would be useful to control legitimate promises use (in debug mode).

https://github.com/lextiz/bluebird/tree/promiseChainLengthLimit

**Comment by bergus** [comment] 2015-12-15 22:48
I don't really see how that could be useful. Why would you want to limit how many promises are chained?

Btw, this seems to implement a chain *length* limit, not a chain *depth* one.

**Comment by lextiz** [comment] 2015-12-16 06:33
What is the difference between these two? I mean longest number of promises between two promises in chain. This feature would be useful to limit sane usage of promises. The limit (like 10000) would apply to promise chains created in loop (like queues). This would warn user about situations which could potentially slow down the UI and consume enormous amount of memory.

**Comment by bergus** [comment] 2015-12-16 07:35
> What is the difference between these two?

Promises don't only chain, they also nest - when you repeatedly resolve a promise with a promise that is resolved with a promise that… etc. If we call this "*nesting*", it has a *depth*. I'm not sure how to name the other (*length*  sounds suitable), but I think we need to distinguish them. Possibly related: http://stackoverflow.com/a/29931657/1048572

**Comment by lidortal** [comment] 2015-12-16 11:12
+1

**Comment by petkaantonov** [comment] 2015-12-16 11:21
> This would warn user about situations which could potentially slow down the UI and consume enormous amount of memory.

Long chains don't cause this in bluebird any more than short chains do.

**Comment by tamirmen** [comment] 2015-12-16 20:10
Promises threshold can provide good notification for developers that they probably have unexpected situation.
The problem is not the promises but rather that they help to identify suspicious logic. It could be similar to limit no. of loops, array length, concurrent threads etc. In all these cases the logic in some point could reach unexpected threshold and the promises mechanism in this case can easily detect it, warn about it, and even stop the situation.

**Comment by benjamingr** [comment] 2015-12-17 18:41
There are lots of patterns that require arbitrary depth because of how assimilation works, I think we'd get a TON of false positives here but if OP is interested in implementing a PoC I'm ready to be proven wrong.

**Comment by lextiz** [comment] 2015-12-17 18:44
POC: https://github.com/lextiz/bluebird/tree/promiseChainLengthLimit

**Closed** 2016-02-12 01:22 UTC
Labels: enhancement, needs-investigation
