### ISSUE TITLE
Using bluebird in IE/Edge does not always resolve promises when window is not focused

### ISSUE THREAD

**Issue by mindlink** [petkaantonov/bluebird#1161] opened 2016-07-12 14:31 UTC
1) What version of bluebird is the issue happening on?
3.4.1

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Internet Explorer 11, Edge

3) Did this issue happen with earlier version of bluebird?
Unknown

Have some operation that triggers regardless of user interaction e.g. long-polling XHR, websocket, setTimeout, that signals a promise chain and nothing else. Then switch from IE/Edge to something else.

You would expect that the promise chain is executed regardless, however the chain stops executing.

Further investigation shows that the use of MutationObserver as the scheduler, means that a DOM change (or console log if the debugger is open) is required to trigger the promise chain. A detached DOM operation does not trigger the chain (like in the MutationObserver scheduler).

We have worked around this issue by setting the scheduler to use setTimeout (which isn't ideal).

**Comment by benjamingr** [comment] 2016-08-27 14:23
We actually use `NativePromise.resolve` if it is available so edge shouldn't be an issue.

As for IE11, I haven't experienced this - is the computer under low power mode or something similar? Note that in low power settings your `setTimeout` workaround might not work. 

We can prefer setImmediate over mutationobserver in IE. A small reproducing example would do wonders.

**Comment by lowkay** [comment] 2016-08-27 14:44
Howdy,

Further investigation into this revealed that the issue is only in a callback from an XHR. Resolving a promise in such a callback without active DOM operations will not trigger the promise chain to execute.

We thus altered our approach to wrap the promise resolution in a setTimeout, then magically it works.

I have a test case, which I'll try and publish on github next week. It seems to affect pretty much every promise library not just bluebird - due to the fact MutationObserver has the closest execution scheduling to native promises.

**Comment by benjamingr** [comment] 2016-08-27 14:50
Oh, so it's an XHR specific issue in IE where it doesn't call the resolution code unless it's wrapped in a timeout? That's interesting.

I don't think it's in scope for bluebird to solve that case though as it's xhr specific.

**Closed** 2016-08-27 22:02 UTC
Labels: environment-scheduler-bug

**Comment by thomas-darling** [comment] 2016-08-28 00:20
@benjamingr can you please elaborate on why this not a bluebird issue?
This is currently prevents our app from loading in IE, and I don't see who else would be in a position to fix this - as I understand it, this is a result of the way bluebird uses MutationObserver for scheduling.

**Comment by benjamingr** [comment] 2016-08-28 06:46
> Further investigation into this revealed that the issue is only in a callback from an XHR. Resolving a promise in such a callback without active DOM operations will not trigger the promise chain to execute.

It sounds like it's specific to XHR, rather than all of IE. It makes sense to poky fill it there differently rather than change the whole scheduler.

**Comment by thomas-darling** [comment] 2016-08-28 19:04
I'm confused - bluebird is a polyfill, and if it does not work properly in IE, then I don't see how closing the issue can be justified. I agree it is likely related to XHR requests, but I don't see how that makes a difference - we still don't know exactly what is wrong or how to fix it, and the `setTimeout` workaround is a horrible hack that has performance implications and may not even work in all scenarios. I think this issue should be kept open until we have a proper fix - and until then, I'd say this is an issue with the choice of scheduler :-)

**Comment by petkaantonov** [comment] 2016-08-29 05:47
it's not a polyfill, the api just has reasonable overlap with native promises

**Comment by benjamingr** [comment] 2016-08-29 06:40
@thomas-darling I have been unable to reproduce this issue with IE11 twice now, if IE11 throttles XHR (and not mutation observers) then the fact it's promises makes no difference.

A reproducing sample would go a _huge_ way here - it's possible this was in earlier bluebird or caused by another computer setting.

**Comment by lowkay** [comment] 2016-09-01 15:02
Howdy,

Here is an example of what we are experiencing, on the left is Chrome doing what you'd expect, on the right is IE 11 neither windows were focused or had mouse interaction until 15:52:07..

Note how the promise is reported as resolved at 15:51:45 but the continuation is only invoked at 15:52:07 - that's 22 seconds later. It would be indefinite if I never interacted with the mouse.

![image](https://cloud.githubusercontent.com/assets/4092982/18172062/1244676a-705c-11e6-97e8-9bf070b93d0a.png)

**Comment by lowkay** [comment] 2016-09-01 15:03
You can find the application that replicates this issue here:
https://github.com/lowkay/MutationObserverSchedulerBug

**Comment by deser** [comment] 2016-12-04 16:23
So was that issue resolved guys?

**Comment by lowkay** [comment] 2016-12-04 16:40
We stuck with a settimeout workaround, its definitely a bug with how IE handles XHR callbacks.

**Comment by deser** [comment] 2016-12-04 16:41
The library then should care about the bug...

**Comment by rgupta2** [comment] 2018-12-31 07:13
Bluebird Promise not working for me on IE11. Was this issue fixed?
