### ISSUE TITLE
How to promisify constructor's handling methods?

### ISSUE THREAD

**Issue by marcellodesales** [petkaantonov/bluebird#558] opened 2015-04-01 22:03 UTC
Hi there,

I'm trying to use Bluebird to the Swagger-js client: https://github.com/swagger-api/swagger-js

```
var client = require("swagger-client")

var swagger = new client.SwaggerClient({
  url: 'http://petstore.swagger.io/v2/swagger.json',
  success: function() {
    swagger.apis.pet.getPetById({petId:1});
  }
});
```

I'm creating a wrapper to return the "apis" object back to the wrapper's clients. I cannot find a way to use the promises for a Constructor handling: `new SwaggerClient({url: url});`... 

I saw that the method resolve worked perfectly, but I'm not sure how to make it call the proper method "success"

```
      var Promise = require("bluebird");
      var SwaggerClient = require("swagger-client");
      Promise.resolve().then(function() {
        return new SwaggerClient({url: url});
      }).then(function(swagger) {
        return swagger;
      }).then(function(swagger) {
        return swagger.api;
      });
```

Could anybody help?

thanks!

**Comment by bergus** [comment] 2015-04-02 00:03
Does that project have some api docs anywhere, or are we expected to read their source to find out how `SwaggerClient` works?
Either way, have a look at the great https://stackoverflow.com/questions/22519784/how-do-i-convert-an-existing-callback-api-to-promises

**Comment by petkaantonov** [comment] 2015-04-02 04:53
Duplicate of https://github.com/petkaantonov/bluebird/issues/528

**Closed by petkaantonov** 2015-04-02 04:53 UTC

**Comment by marcellodesales** [comment] 2015-04-02 07:01
@bergus they definitely have documentation... As I'm learning about it, I thought that making anything using promises did not include reading their API, but only the method signature... :)

Anyway, I will definitely look at the documentation... I was just hoping to learn by examples... 

thanks!

**Comment by marcellodesales** [comment] 2015-04-02 07:50
Just realized that this API does not follow the "node" way of callback. If you notice, the API has the parameter being an option, where the callback function for success is the "success" property of the parameter. :(

**Comment by petkaantonov** [comment] 2015-04-02 07:53
@marcellodesales Have you looked at [custom promisifier section](https://github.com/petkaantonov/bluebird/blob/master/API.md#option-promisifier) in the api?

**Comment by marcellodesales** [comment] 2015-04-02 07:55
@petkaantonov let me take a look...

**Comment by marcellodesales** [comment] 2015-04-02 11:27
@petkaantonov Can you point out the documentation on what you described as anti-pattern? I'm still learning this...

thanks for the tip!

**Comment by petkaantonov** [comment] 2015-04-02 11:31
https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern
