### ISSUE TITLE
IE 10: Object "P" is undefined

### ISSUE THREAD

**Issue by tflanagan** [petkaantonov/bluebird#859] opened 2015-11-09 15:00 UTC
Hey,

Per the docs, `the script tag installation exposes the library in the Promise and P namespaces.`

I am not doing it the usual way, because of the environment I am working in, I am executing this (after page load):

```javascript
$('<script />', {
	type: 'text/javascript',
	src: 'bluebird/js/browser/bluebird.min.js'
}).appendTo('head')
```

This works great in Chrome, Firefox, etc, and exposes the library as stated in the docs but fails in IE 10:

![p_undefined](https://cloud.githubusercontent.com/assets/5559820/11036695/1eebe232-86c8-11e5-8ad4-bcec92f5c3b7.png)

When in the console (again, IE 10), I tried loading it and got this error:

![require png](https://cloud.githubusercontent.com/assets/5559820/11036775/7645857e-86c8-11e5-8c9b-9177fa731d4d.png)

**Comment by bergus** [comment] 2015-11-09 19:21
Using require.js (as you seemt to do in IE) is not exactly the "script tag installation".

**Comment by tflanagan** [comment] 2015-11-09 19:28
My wording does seem to couple these, but that is not my intent.

The console ```require``` was an attempt to debug the issue and is not used in code.

**Comment by benjamingr** [comment] 2015-11-10 08:10
Can't reproduce, can you share code that's causing this?

**Comment by petkaantonov** [comment] 2015-11-10 11:48
The browser build is UMD, if it detects require.js or common.js nothing will be exported to global

**Comment by benjamingr** [comment] 2015-11-11 11:23
Closing because I can't reproduce and Petka's words makes sense - if you have `require` it will use that instead and not declare a global.

**Closed by benjamingr** 2015-11-11 11:23 UTC
