### ISSUE TITLE
Memory leaking with Promise.map concurrency

### ISSUE THREAD

**Issue by samclearman** [petkaantonov/bluebird#1557] opened 2018-10-22 19:00 UTC
1) What version of bluebird is the issue happening on?
Bluebird 3.5.20 with bluebird-global 3.5.5

2) What platform and version? (For example Node.js 0.12 or Google Chrome 32)
Node.js 8.9.

3) Did this issue happen with earlier version of bluebird?
As far as I know

I have code that looks like this:

```
const aBunchOfIds = [ /* a few hundred thousand elements */ ]
Promise.map(aBunchOfIds, async id => {
    const anObj = await getFromDatastore(id);
    const anotherObj = await process(anObj);
    if (isSpecial(anotherObj)) { console.log('so special'); }
}, { concurrency: 1000 });
```

This dies because node runs out of heap space.  However the following modification resolves the issue:

```
const aBunchOfIds = [ /* a few hundred thousand elements */ ]
for (let i = 0; i < aBunchOfIds.length; i += 10000) {
    const someIds = aBunchOfIds.slice(i, i + 10000);
    Promise.map(someIds, async id => {
        const anObj = await getFromDatastore(id);
        const anotherObj = await process(anObj);
        if (isSpecial(anotherObj)) { console.log('so special'); }
    }, { concurrency: 1000 });
}
```

So it seems that Promise.map doesn't free the memory used by its promises until all promises have returned, even when a concurrency is specified.

**Comment by benjamingr** [comment] 2018-10-23 11:11
> So it seems that Promise.map doesn't free the memory used by its promises until all promises have returned, even when a concurrency is specified.

That's the queue shrinking and growing - it's a static overhead and not nwe :) 

If you run this multiple times it won't grow again - it's just reserving memory in the background so future executions are allocation free.

**Comment by benjamingr** [comment] 2018-10-24 11:49
I'll test it and make sure this is what we do.

**Comment by samclearman** [comment] 2018-11-02 01:42
I guess it's possible that it's just `100000 * promise_size` that is blowing up my heap but that doesn't seem right to me, I suspect that the variables allocated in the functions that promises call aren't getting garbage collected until the whole thing finishes?

**Comment by spion** [comment] 2018-11-02 12:34
Seems to me that as long as memory usage is contained within the callback it gets GCed correctly: https://jsfiddle.net/w03ykabx/3/

**Comment by krunkosaurus** [comment] 2019-01-03 23:05
Just a heads up that I got "Maximum call stack size exceeded" errors until I finally downgraded this package to 3.5.2 

I think it could be related to this issue.

**Comment by gebrits** [comment] 2019-02-02 13:51
I'm seeing memory-leak issues that are very similar, if not the same. 

Came up with the following test which shows the issue clearly: 

- running below code as-is will result in OOM in a couple of seconds
- running code with `then()` added (see  below) will allow GC to free up mem. Why is this needed?

```

/*
 Below gives an OOM in a couple of seconds. 
 Adding the commented-out then() solves it. Why?
 */
const Promise = require("bluebird");
const obj = {a: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"};
return Promise.map(new Array(100000), () => {
  return Promise.resolve()
  .then(() => new Array(10000).map(() => Object.assign({},obj))) //consume some mem
  // .then(() => {
  //   //adding this then(), will allow objects to be GC'ed, thus solving OOM-issue. WHY?
  // });
}, { concurrency: 10 })

```

**Comment by samclearman** [comment] 2019-02-02 19:14
Nice repro!

**Comment by shivaalroy** [comment] 2019-05-07 03:51
@samclearman I believe I've found an easy fix for this:

repro code:
```
import 'bluebird-global';

const ids = fnThatGetsIds;
let done = 0;
await Promise.map(ids, async id => {
  const record = await getLargeRecord(id);
  if (done % 100 === 0) {
    console.log(done, new Date().getTime() - time);
    time = new Date().getTime();
  }
  done++;
  // starts slowing down after (~2mins)
}, { concurrency: 100 });
```
This slows down after 2 minutes.

Adding `return Promise.resolve();` fixes the issue, and there's no slowdown.
```
import 'bluebird-global';

const ids = fnThatGetsIds;
let done = 0;
await Promise.map(ids, async id => {
  const record = await getLargeRecord(id);
  if (done % 100 === 0) {
    console.log(done, new Date().getTime() - time);
    time = new Date().getTime();
  }
  done++;
  return Promise.resolve(); // doesn't slow down
}, { concurrency: 100 });
```
Removing the `return` causes a slow down, and `return null;` also causes a slow down.

**Comment by samclearman** [comment] 2019-05-07 06:29
Thanks @shivaalroy .  Looks like that agrees with what @gebrits was seeing...  @benjamingr, can you comment on whether this is intended behavior or not?

**Comment by benjamingr** [comment] 2019-05-07 07:06
That... makes no sense 😅

**Comment by w9jds** [comment] 2019-05-17 19:06
I am seeing similar behavior as well. I have a Kubernetes service running with a map with concurrency running every ~6-10 seconds. After a couple hours the memory heap doubles (rinse repeat). Eventually it causes Kubernetes to try and boot up more containers and evicts all of them for lack of memory. When I remove the map command, and loop through them myself with Promise.all the memory issue goes away.

**Comment by petkaantonov** [comment] 2019-05-25 16:59
I'm not sure what the problem is. `.map` will store the result of the mapping function until the entire map has run. If this result takes a lot of memory then you will run out of memory if you cannot hold all the results. If you don't need to store the result to use it from the final mapped array then don't return it from the mapping function.

**Comment by benjamingr** [comment] 2019-05-25 17:06
@petkaantonov then why would this leak memory:


```js
import 'bluebird-global';

const ids = fnThatGetsIds();
let done = 0;
await Promise.map(ids, async id => {
  const record = await getLargeRecord(id);
  if (done % 100 === 0) {
    console.log(done, new Date().getTime() - time);
    time = new Date().getTime();
  }
  done++;
  // starts slowing down after (~2mins)
}, { concurrency: 100 });

```

**Closed by benjamingr** 2019-05-25 17:06 UTC

**Comment by officert** [comment] 2022-10-22 13:40
I'm seeing the same thing happening with Promise.map() using v3.7.2. I have some logging in place and I'm seeing things slowing down until they just stall before completing. I'm going to give [shivaalroy](https://github.com/shivaalroy)'s answer a try. No idea why that would make a difference, doesn't make sense......but worth a shot. Will report back.
