### ISSUE TITLE
Wrapper to Join on all function's arguments

### ISSUE THREAD

**Issue by mdarveau** [petkaantonov/bluebird#720] opened 2015-08-04 04:21 UTC
Hi,

First of all, thank you for this excellent library.

When I have a function that can receive a resolved value or a promise, I often find myself doing the following:
```
exports.doSomething = ( valueOrPromise1, valueOrPromise2 ) ->
  Bluebird.join valueOrPromise1, valueOrPromise2, ( value1, value2 ) ->
    value1.something()
    value2.somethingElse()
```

I finally created a little wrapper that automatically join all my functions params and then call the function that works on resolved values (coffeescript + lodash):
```
joinArgs = (f)->
  _.partialRight(Bluebird.join, f);

exports.doSomething = joinArgs ( value ) ->
  value.something()
```

What do you think of adding the `joinArgs` utility to Bluebird? I can work out the PR but don't want to waste anyone's time if you don't think it belongs to the lib. Maybe joinWrap or wrapJoin would be a better name?

**Comment by bergus** [comment] 2015-08-04 20:02
`lift` would be an appropriate name.

**Comment by spion** [comment] 2015-08-04 21:49
FWIW, my experience is that lifted functions can work well locally but the ability to take promises as arguments gets confusing really fast. Built in functions and operators can't do it, and neither can auto-promisified libraries, so you can easily end up with an API that consists of a mix of lifted and unlifted methods. Thats pretty difficult to deal with (unless you use a typed dialect such as typescript/flowtype)

**Comment by petkaantonov** [comment] 2015-09-08 22:59
Duplicate of https://github.com/petkaantonov/bluebird/issues/78

<hr>

Some things to help figure out how useful addition this would be to core:

1. Do you use this often in your projects? Or just a lot in one project? Or just once in many projects?

2. Are there any other people that would be interested in this?

3. Can it be used as a generic build block that you can build on top of instead of being a specialized tool for some specific scenarios?

**Comment by bergus** [comment] 2015-09-10 15:04
I'd be interested too. I'd say it's seldom used in many projects - frequency depending on programming style. As @spion says, functions that take promises as arguments (when they don't really require it) are rather confusing in an API. It would be helpful for internal functions though.
I think it's as generic as `Promise.join` as a building block, the only difference is that `Promise.lift` would be curried.

**Comment by mdarveau** [comment] 2015-09-11 01:37
I only have one node project that uses Promise extensively. However, I use "lift" a lot in services that can be called by different endpoints/resources/context.

I use the Sequelize ORM and I often need to pass database objects to various services that will transform them. For example, if I have a service that accepts a `User` and an array of `Task`, I can call it with previously loaded `User` and `Task`s, pass a previously loaded `User` but a Promise of `Task`s. Without `lift`, I need to force a reload of records in the service (useless database calls) or implement some sort of `join` in the method which is just boilerplate.

**Comment by tjconcept** [comment] 2015-10-29 18:43
As others mention, I find it confusing most of the time and it's easy to avoid by using `join` or `resolve` at call site.

One argument could be that a function with multiple parameters could "start the work" before all of them had resolved - a "lift" method would counter that though.

**Comment by spion** [comment] 2015-10-29 21:46
Given `function service(user, tasks) { }`

And the promises `user` and `tasks`

The code to use the service is just:

```js
var result = Promise.join(user, Promise.all(tasks), service)
```

Would I increase the complexity of the service function just to be able to say

```js
var result = service(user, Promise.all(tasks))
````

No, I would not.

**Comment by petkaantonov** [comment] 2015-11-04 11:41
The comments here, and my own opinion as well, is that's it's overall not a justified addition, so closing this issue for now

**Closed by petkaantonov** 2015-11-04 11:41 UTC
Labels: enhancement, pending-author-input
