### ISSUE TITLE
Promise.using doesn't work with cancellation as expected.

### ISSUE THREAD

**Issue by Page-** [petkaantonov/bluebird#537] opened 2015-03-20 15:10 UTC
```javascript
var Promise = require('bluebird'),
	createDisposer = function() {
		Promise.resolve().disposer(function() {
			console.log('disposer called')
		});
	};

console.log('using');
var p = Promise.resolve().cancellable().then(function() {
	return Promise.using(createDisposer(), function() {
		console.log('1');
		return Promise.try(function() {
			console.log('2');
		})
		.cancellable()
		.delay(2000)
		.then(function() {
			console.log('3');
		})
		.catch(Promise.CancellationError, function(e) {
			console.log('cancelled 1', e);
			throw e;
		})
		.then(function() {
			console.log('4');
		})
	})
	.cancellable()
	.then(function() {
		console.log('5');
	})
	.catch(Promise.CancellationError, function(e) {
		console.log('cancelled 2', e);
		throw e;
	});
})
.then(function() {
	console.log('6');
})
.catch(Promise.CancellationError, function(e) {
	console.log('cancelled 3', e);
})
p.cancel();

Promise.delay(5000).then(function() {
	console.log('try');
	var p = Promise.resolve().cancellable().then(function() {
		return Promise.try(function() {
			console.log('1');
			return Promise.try(function() {
				console.log('2');
			})
			.cancellable()
			.delay(5000)
			.then(function() {
				console.log('3');
			})
			.catch(Promise.CancellationError, function(e) {
				console.log('cancelled 1', e);
				throw e;
			})
			.then(function() {
				console.log('4');
			})
		})
		.cancellable()
		.then(function() {
			console.log('5');
		})
		.catch(Promise.CancellationError, function(e) {
			console.log('cancelled 2', e);
			throw e;
		});
	})
	.then(function() {
		console.log('6');
	})
	.catch(Promise.CancellationError, function(e) {
		console.log('cancelled 3', e);
	})
	p.cancel();
});
```
results in
```
using
1
2
cancelled 2 [CancellationError: cancellation error]
cancelled 3 [CancellationError: cancellation error]
3
4
try
1
2
cancelled 1 [CancellationError: cancellation error]
cancelled 2 [CancellationError: cancellation error]
cancelled 3 [CancellationError: cancellation error]
```
Whereas I would expect:
```
using
1
2
cancelled 2 [CancellationError: cancellation error]
cancelled 3 [CancellationError: cancellation error]
try
1
2
cancelled 1 [CancellationError: cancellation error]
cancelled 2 [CancellationError: cancellation error]
cancelled 3 [CancellationError: cancellation error]
```
with the promise returned within the `Promise.using` function being correctly cancelled.

**Comment by petkaantonov** [comment] 2015-03-20 15:40
cancellation in 2.x is horribly broken by design and wontfix and cannot be made to work with all bluebird features consistently. Cancellation has been redone for 3.0

**Closed by petkaantonov** 2015-03-20 15:40 UTC
