### ISSUE TITLE
Bluebird on SlimerJS and PhantomJS, rejected with a non-error: [object Error]

### ISSUE THREAD

**Issue by manbaum** [petkaantonov/bluebird#855] opened 2015-11-08 06:04 UTC
```JavaScript
var Promise = require("./bluebird"); // * bluebird build version 3.0.5
new Promise(function(resolve, reject) {
	try {
		var a = an_undefined_variable;	// test 1, error thrown by JavaScript engine.
		// throw new Error("1");		// test 2, error thrown by code.
	} catch (ex) {
		reject(ex);
	}
	// reject(new Error("2"));			// test 3, error constructed directly.
}).caught(function() {});
```
On [SlimerJS 0.9.6](http://slimerjs.org/) or [PhantomJS 2.0.0](http://phantomjs.org/), All 3 tests will cause a warn: ```Warning: a promise was rejected with a non-error: [object Error]```, but on [NodeJS 4.2.1](https://nodejs.org/), everything is ok.

I don't know it's a bug of Bluebird, or of SlimerJS and PhantomJS.

**Comment by manbaum** [comment] 2015-11-08 13:02
I also submitted this issue: [Strange behavior of "instanceof Error"](https://github.com/laurentj/slimerjs/issues/400).

**Comment by benjamingr** [comment] 2015-11-11 11:29
I guess this can be fixed by removing the `instanceof` check in https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L242 or checking classString against `[object Error]`.

I guess that this is caused by Phantom and Slimer having two instances of `Error`.

**Comment by petkaantonov** [comment] 2015-12-15 20:26
Any subclassed error is not `[object Error]` so this cannot be fixed

**Closed by petkaantonov** 2015-12-15 20:26 UTC
Labels: 3.0.0, bug, fix-in-progress
