### ISSUE TITLE
Memory leak trying to create a while loop with promises

### ISSUE THREAD

**Issue by colmaengus** [petkaantonov/bluebird#502] opened 2015-02-19 09:25 UTC
I'm trying to create a while loop using promises and I'm getting a memory leak.
An example of the pattern I'm using is 

```javascript
var promiseFor = BPromise.method(function(delay, condition, action, value) {
  if (!condition(value)) {
    return value;
  } else {
    return action(value).delay(delay).then(promiseFor.bind(null, delay, condition, action));
  }
});

var condition = function(value) {
  return value != 100000;
};

var action = function(value) {
  return BPromise.delay(10)
    .then(function() {
      console.log('value:' + value);
      return value + 1;
    });
};

var delay = 0;

promiseFor(delay, condition, action, 0)
  .then(function() {
    console.log('done');
  })
  .catch(function(e) {
    console.error(e.message);
  });
```
When I run this the memory used by node keeps increasing.
I'm using bluebird 2.9.10.
I've tried another approach to avoid the recursive nature of the approach above but it also has a leak.
Any suggestions on how to correctly implement a promise while loop ?

**Comment by benjamingr** [comment] 2015-02-19 09:38
Here is how I'd implement a while loop using bluebird:

```js
var promiseWhile  = BPromise.coroutine(function(delay, condition, action, value) {
    while(!condition(value){
          value = yield condition(action(value));
          yield Promise.delay(delay);
    }
});
```

**Comment by colmaengus** [comment] 2015-02-19 11:34
Looks nice but unfortunately for now we are using node 0.10 so we can't use generators.

**Comment by petkaantonov** [comment] 2015-02-19 11:45
There is no need to implement any helper in the first place, just use recursion

```js
(function loop(value) {
  if (value != 100000) {
    return Promise.delay(10).then(function() {
      console.log('value:' + value);
      return value + 1;
    }).then(loop);
  }
})(0);
```

**Comment by colmaengus** [comment] 2015-02-19 12:48
@petkaantonov unfortunately this approach also has a leak. On windows the node process gained about 14 MB in 20 mins. I'm looking for some way to keep running a promise function over a long period of time without leaking memory.

**Comment by petkaantonov** [comment] 2015-02-19 12:54
@colmaengus It appears you are not actually using 2.9.10 then. Can you log this for me and let us know what it logs:

```js
console.log(BPromise.prototype._rejectCallback + "");
```

**Comment by colmaengus** [comment] 2015-02-19 13:30
```javascript
function (reason, synchronous, shouldNotMarkOriginatingFromRejection) {
    if (!shouldNotMarkOriginatingFromRejection) {
        util.markAsOriginatingFromRejection(reason);
    }
    var trace = util.ensureErrorObject(reason);
    var hasStack = trace === reason;
    this._attachExtraTrace(trace, synchronous ? hasStack : false);
    this._reject(reason, hasStack ? undefined : trace);
}
```

**Comment by petkaantonov** [comment] 2015-02-19 13:34
Ok so we are surely using the same version then. I cannot reproduce any memory leak. Just to make sure we are on the same page here, can you run this:

```js
var Promise = require('bluebird');

function immediate() {
    return new Promise(function(resolve) {
        setImmediate(resolve);
    });
}

(function loop(value) {
    return immediate().then(function() {
      if (value % 10000 === 0) {
        console.log(process.memoryUsage().heapUsed, value);
      }
      return value + 1;
    }).then(loop);
})(0);
```

**Comment by petkaantonov** [comment] 2015-02-19 13:40
I ran it until 1110000 (equal to having the original code run for 3 hours) and the heap usage is almost same as when it started.

**Comment by colmaengus** [comment] 2015-02-19 14:21
That seems to be pretty stable. The node process memory climbed to 44,304 K and pretty much stays there.
![image](https://cloud.githubusercontent.com/assets/6358852/6268108/00aa5aec-b842-11e4-8655-68b6b1026b17.png)
The heapUsed also seems pretty stable.
There are a few places I need to use this and in some cases the check condition uses a class function so I need a clean way to pass 'this' around while trying to keep the code readable.

**Comment by petkaantonov** [comment] 2015-02-19 14:46
So do you agree there is no memory leak?

**Comment by petkaantonov** [comment] 2015-02-19 15:14
Ok somehow the original code is not equivalent to the straight-forward recursion example and it indeed leaks : https://gist.github.com/petkaantonov/b73d52b9092b6f857271

**Comment by colmaengus** [comment] 2015-02-19 15:22
I agree there is no memory leak leaving the interesting question of how to use while loop in practice.

**Comment by petkaantonov** [comment] 2015-02-19 15:31
Well you can use your original code or my code.

It leaks when there is a .then() added for the console.log("Done"); but this didn't leak in 2.5.2 which fixed the original memory leak issue with promises in general.

**Comment by colmaengus** [comment] 2015-02-19 15:34
Many thanks for your help. I let you know how I get on.

**Comment by petkaantonov** [comment] 2015-02-19 15:41
This memory leak was introduced in 2.8.2 -> 2.9.0.

So you could use earlier version before I fix it (2.8.2)

**Comment by petkaantonov** [comment] 2015-02-19 16:17
Fixed in 2.9.12

**Comment by robey** [comment] 2015-06-27 01:17
I hate to pile on, but I think I'm running into another form of the same bug, using recursion as a while loop: https://gist.github.com/robey/de6717a41734d802c864

```
20.26 mb 1
34.39 mb 2
47.85 mb 3
67.94 mb 4
80.96 mb 5
99.04 mb 6
110.18 mb 7
123.17 mb 8
136.16 mb 9
156.67 mb 10
169.56 mb 11
182.55 mb 12
194.06 mb 13
```

**Comment by robey** [comment] 2015-06-27 01:19
removing the "catch" block also removes the leak. weird.

**Comment by robey** [comment] 2015-06-29 18:29
This variant also works around it, which I'm using now:

```
    return get().catch(function (error) {
      active = false;
    }).then(function () {
      return active ? loop() : Promise.resolve();
    });
```

**Comment by petkaantonov** [comment] 2015-07-01 19:00
@robey That is not a similar bug or a bug at all. In the original bug all the promises have settled before starting the next iteration -  there is no way to reach them and any memory used by them is therefore considered memory leak.

In your code you are creating an additional promise before moving on to the next iteration. This additional promise you create can only be settled after the loop has ended and the code will then reach all of them therefore all those promises have to be kept around thus it's not a memory leak.

Let's write 5 iterations of your loop manually with logs placed:

```js
function get() {
    return Promise.delay(5);
}

return get().then(function (v) {
    return get().then(function (v) {
        return get().then(function (v) {
            return get().then(function (v) {
                return get().then(function (v) {
                    console.log("finished loop");
                }).then(function (error) {
                    console.log("1 reached");
                });
            }).then(function (error) {
                console.log("2 reached");
            });
        }).then(function (error) {
            console.log("3 reached");
        });
    }).then(function (error) {
        console.log("4 reached");
    });
}).then(function (error) {
    console.log("5 reached");
});
```

This will log:

```
finished loop
1 reached
2 reached
3 reached
4 reached
5 reached
```

Which clearly shows that the promises (and their callbacks) must be reachable *after* the loop ends.

**Closed by petkaantonov** 2015-07-01 19:00 UTC
Labels: needs-investigation

**Comment by petkaantonov** [comment] 2015-07-01 19:06
@robey also using .catch for every iteration as you have done has actually no good purpose here. Rejection during any iteration of the loop will already stop the loop even if you place no catch at all.

**Comment by robey** [comment] 2015-07-02 04:38
so my workaround fixes my own bug by making sure the loop is the last call in the promise. makes sense; thanks for digging into it! :)
