### ISSUE TITLE
Memory leak on IE 10 & 11

### ISSUE THREAD

**Issue by zomaish** [petkaantonov/bluebird#669] opened 2015-06-23 21:44 UTC
```html
<!DOCTYPE html>
<html>
<head></head>
<body>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/2.9.30/bluebird.min.js"></script>
</body></html>
```

If we load this file in IE 10/11 we will notice that memory allocation will grow in task manager with every refresh

**Comment by stefanpenner** [comment] 2015-06-23 23:17
That sounds like a browser bug....

**Comment by benjamingr** [comment] 2015-06-24 06:46
There is nothing bluebird can do here nor anything it does.

If I had to guess - you have the developer tools open when you do it, but I really can't tell with only so much. Does it not happen with other libraries?

(I can't reproduce this on IE11 by the way)

**Comment by stefanpenner** [comment] 2015-06-24 13:54
I'm the past I have seen mutation observers retain the DOM between page reloads. This seems to have been fixed in chrome ages ago. But it was possible to work around by detaching on unload.  Let me grab my laptop and pull up that old code

**Comment by davydog187** [comment] 2015-06-24 14:19
It most definitely is a browser bug, we're just curious as to what may be causing it. @stefanpenner I would be interested to see your findings

**Comment by stefanpenner** [comment] 2015-06-24 16:16
My first suggestion would be to remove the MutationObserver code, and fall back to some other async. See if that is the source of the leak. I am unsure if that is actually the leak, only it has been a leak in other browsers. So it seems likely?

I wont have time to dig into this, I merely providing details on a similar issue i had.

Old PR: https://github.com/emberjs/ember.js/commit/d39c1e1754eb93d8ac06d9ae50e1ead66cf7d310

**Comment by benjamingr** [comment] 2015-06-24 16:18
Note that bluebird supports this outside of core using `setScheduler`, you
can test this yourself in your own code by doing something like:

```js
Promise.setScheduler(function(fn){
    setImmediate(fn); // setImmediate works in ie as far as I recall
});
```

And see if it still leaks.

**Comment by stefanpenner** [comment] 2015-06-24 16:28
be careful a quick skim suggest  the schedule code always invokes. Even if it custom scheduler is used.

**Comment by zomaish** [comment] 2015-06-24 19:08
After some tests, I believe the issue is in document.createEvent("CustomEvent"); that is deprecated according to https://msdn.microsoft.com/en-us/library/dn905219(v=vs.85).aspx.

if we do something like
if (document.createEventObject) {
   event = document.createEventObject();
} else {
  event = document.createEvent("CustomEvent");
}

document.createEventObject(); will return a [object MSEventObject] where  document.createEvent("CustomEvent"); will return a [object CustomEvent] and my guess the later is causing IE to hold on to the dom

**Comment by stefanpenner** [comment] 2015-06-24 19:16
Oh crazy!

**Comment by zomaish** [comment] 2015-06-24 21:05
Opened https://github.com/petkaantonov/bluebird/pull/671 with a fix.
To reproduce the issue in IE10 at least, load bluebird by itself in a webpage, and after a few minutes keep refreshing IE, you will see memory growth in task manager

**Comment by benjamingr** [comment] 2015-06-24 21:06
Thanks, I've added some comments to the PR, this will also need porting to the 3.0 branch.

**Comment by petkaantonov** [comment] 2015-07-04 10:20
Closing as there is no memory leak even after ~4300 refreshes using:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
</head>
<body>
<body>
<script type="text/javascript" src="js/browser/bluebird.min.js"></script>
<script type="text/javascript">
setTimeout(function() {
   document.location.reload();
}, 100);
</script>
</body>
</body>
</html>
```

I let this run for about ~430 seconds and the memory usage of the process stays stable:

![memoryusage](https://cloud.githubusercontent.com/assets/829734/8507510/48e7a428-224f-11e5-985a-bedb0e6c4b2e.png)

**Closed by petkaantonov** 2015-07-04 10:20 UTC
Labels: pull-request-done
