### ISSUE TITLE
Feature request: Promise.times(n, callback)

### ISSUE THREAD

**Issue by hulbert** [petkaantonov/bluebird#1264] opened 2016-10-17 23:58 UTC
In the spirit of Bluebird helping with terser promise usage (things like `.get('propertyName')`) it'd be lovely to add a method that would behave nearly the same as map but would iterate `n` times without requiring the user to create an array to iterate first.

Example:

```
Promise.times(1000, function() {
    console.log(arguments[0]) // logs 'undefined'
    return Promise.resolve()
})
```

This usage came up as being useful in a test function that seeds data. Lodash has its `_.times` method which behaves like `_.map` (collects returned results) but takes a number as its first argument.

**Comment by bergus** [comment] 2016-10-18 01:22
Duplicate of #1053

**Closed** 2016-10-18 02:56 UTC
