### ISSUE TITLE
bluebird 3 made testing much more complicated

### ISSUE THREAD

**Issue by globexdesigns** [petkaantonov/bluebird#906] opened 2015-12-08 16:49 UTC
After upgrading to bluebird v3, our application has a ton of test failures because something has changed in the way Promises are processed.

Consider the following:

```javascript
var SomeMethod = () => {
    runPromise()
        .catch(() => {
            doSomething();
        });
}

it("this test used to pass in v2, but no longer works in v3", (done) => {
    // Spy on `doSomething()`
   const somethingSpy = spyOn(window, 'doSomething'); 

    // Replace promise with a fake one that resolves immediately
   spyOn(window, 'runPromise').and.callFake(() => Promise.reject());

    // Run our method
    SomeMethod();

    // Ensure `doSomething()` was called
    setTimeout(() => {
        expect(somethingSpy).toHaveBeenCalled();
        done();
    }, 0);
})

it("this what we now have to change our tests to in order to get them to pass in v3", (done) => {
    // Spy on `doSomething()`
   const somethingSpy = spyOn(window, 'doSomething'); 

    // Replace promise with a fake one that resolves immediately
   spyOn(window, 'runPromise').and.callFake(() => Promise.reject());

    // Run our method
    SomeMethod();

    // Ensure `doSomething()` was called
    setTimeout(() => {
        setTimeout(() => {
            expect(somethingSpy).toHaveBeenCalled();
            done();
        }, 0);
    }, 0);
})
```

Note the double nested timeouts in the last section here. Why is this needed in the new version of bluebird? It seems to be executing several things asynchronously whereas bluebird v2 only had a single async call.

**Comment by bergus** [comment] 2015-12-08 17:01
While I don't know what caused the difference, I'd recommend that `SomeMethod` should return a promise so that you can hook onto that:
```js
var SomeMethod = () => runPromise().then(doSomething);

it("this is what the test could look like", (done) => {
    // Spy on `doSomething()`
    const somethingSpy = spyOn(window, 'doSomething'); 

    // Replace promise with a fake one that resolves immediately
    spyOn(window, 'runPromise').and.callFake(() => Promise.resolve());

    // Run our method
    return SomeMethod().then(function() {
        expect(somethingSpy).toHaveBeenCalled();
    });
})
```

**Comment by globexdesigns** [comment] 2015-12-08 17:07
SomeMethod in this case doesn't return anything on purpose. In my case SomeMethod is actually a Flux Action which are not supposed to return anything by design.

Another thing, I noticed -- it seems the nested timeout is only needed for testing `reject()` callback but is not needed for `resolve()` callbacks.

**Comment by petkaantonov** [comment] 2015-12-08 17:54
What 2.x version are you comparing to specifically?

**Comment by globexdesigns** [comment] 2015-12-08 17:55
v2.10.2 is what we were using before.

**Comment by petkaantonov** [comment] 2015-12-08 18:12
I cannot reproduce. In both, 2.10.2 and 3.0.6, this gives random result:

```js
var Promise = require("bluebird");
var wasCalled = false;

function doSomething() {
    wasCalled = true;
}

function runPromise() {
    return Promise.reject();
}

function someMethod() {
    runPromise()
        .catch(function() {
            console.log("doing something");
            return doSomething();
        });
}

someMethod();

setTimeout(function() {
    // This is true or false regardless of version, totally random
    console.log(wasCalled);
}, 0);
```

**Comment by globexdesigns** [comment] 2015-12-08 18:27
Interesting. It appears to have something to do with `.then()` calls as well. I have created a JSFiddle here: http://jsfiddle.net/vz4jLfug/

```javascript
var wasCalled = false;

function doSomething() {
    wasCalled = true;
}

function someMethod() {
    new Promise(function (resolve, reject) {
    	if (true) {
        reject(new Error('test'));
      }
    })
    // If you remove this `.then()` block, then both
    // '1' and '2' will fire with true. But if you leave it,
    // Then '1' call is returned with 'false'.
    .then(function () {
      console.log('another thing');
    })
		.catch(function () {
      console.log("doing something");
      return doSomething();
    });
}

someMethod();

setTimeout(function() {
    console.log('1', wasCalled);
  	setTimeout(function() {
		    console.log('2', wasCalled);
    }, 0); 
}, 0);
```

**Comment by grantila** [comment] 2015-12-09 09:30
All your tests here are broken by design @globexdesigns as you are not awaiting promises properly but instead rely on *timing sensitive* logic that may or may not work depending on situations not you or anybody else has any control over. This has nothing to do with bluebird. It's a bit funny though, that you might have found bluebird v3 to actually be a bit slower than v2 (at least in terms of triggering the chains). You experiencing this problem could have happened with a minor upgrade of any other library or node.js itself.

Anyway, to fix your code, let `someMethod` return its promise chain and then await it in your test:

```js
someMethod()
.finally( _ => {
    expect(somethingSpy).toHaveBeenCalled();
    done(); // You should probably let your unit testing framework handle promises too, and not call done yourself.
} )
```

**Comment by petkaantonov** [comment] 2015-12-09 11:45
In your jsfiddle I am getting `true` for both. Anyway, @grantila explained what the problem is, so closing.

**Closed by petkaantonov** 2015-12-09 11:45 UTC

**Comment by globexdesigns** [comment] 2015-12-09 16:31
@grantila I agree that the way this test is written is not 100% reliable, but given that I definitely do NOT want to return the Promise out of my method (by design), I have no other way to access the Promise chain from my test, and as such, no way to attach a callback to it. Using timeouts is the only simple solution I have found to work so far.

@petkaantonov Upon further testing, I can still consistently seeing this output from my JSFiddle:

```
1 false
doing something
2 true
```

but only on Chrome 47 Mac. Firefox 42 Mac results in true/true.

I suppose the only way to reliably test this is to write some middleware for the Promise object itself so I can attach tests to it without relying on holding on a reference to it.

Thanks for your time and feedback.
