### ISSUE TITLE
`promisify()` behavior with multiple parameters can break compatibility

### ISSUE THREAD

**Issue by julien-f** [petkaantonov/bluebird#307] opened 2014-08-28 10:30 UTC
Current behavior of [`promisify`](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function) is to resolve to an array when there is more than one result to the callback.

Unfortunately, if a function is changed to return two or more results instead of one, it breaks the compatibility of the promisified version.

```javascript
var assert = require('assert');
var promisify = require('bluebird').promisify;

// Original function returning one result.
function version1(cb) {
  process.nextTick(function () {
    cb(null, 'foo');
  });
}

// Updated function returning two results.
function version2(cb) {
  process.nextTick(function () {
    cb(null, 'foo', 'bar');
  });
}

// The compatibility is maintained when using callbacks.
function validateWithCallback(fn) {
  fn(function (err, foo) {
    assert.equal(foo, 'foo');
  });
}
validateWithCallback(version1);
validateWithCallback(version2);

// The compatibility is broken when using the promisified version.
function validateWithPromise(fn) {
  promisify(fn)().then(function (foo) {
    assert.equal(foo, 'foo');
  });
}
validateWithPromise(version1);
validateWithPromise(version2);
```

I think the correct approach would be to have an option to force to either return only the first result or to always return an array.

**Comment by nsabovic** [comment] 2015-03-13 06:23
I've been hit by this when using the mongodb driver.

Depending on the operation and result, it sometimes calls the callback with two parameters and sometimes with three. So I will sometimes get back a promise that resolves to one value (which I need), and sometimes to array of two values, of which the second one I don't need. Now the problem is that the value that I need can *sometimes* be an array, too. So when I get an array, I have no way of knowing if it's the result that I want (that's an array), or if the promisify function jumbled the other parameter in there too.

The root of the problem is that the shape of the value is decided at the invocation time instead of at the promisification time, and there's no way to make it fixed (either give me an array always, or give me just the second parameter always).

Sorry for resurrecting an ancient issue.

**Comment by petkaantonov** [comment] 2015-03-13 10:33
@nsabovic Yes this is fixed in 3.0, it cannot be fixed in 2.x because it's a blatantly backward incompatible change

**Comment by nsabovic** [comment] 2015-03-24 00:00
Awesome! Where is 3.0? npm has 2.9 something, 3.0 branch in github also says 2.9 in package.json...

**Comment by petkaantonov** [comment] 2015-03-24 01:05
3.0 is not released yet, it's under development

**Comment by cstyan** [comment] 2015-08-11 17:35
Any update on when this issue might be fixed via the 3.0 release?

**Comment by petkaantonov** [comment] 2015-10-27 14:36
Fixed in 3.0 release

**Closed by petkaantonov** 2015-10-27 14:36 UTC
Labels: 3.0.0

**Comment by gajus** [comment] 2015-11-10 16:27
@petehunt can you give some insights into how mysql is supposed to be promisified now?

**Comment by petkaantonov** [comment] 2015-11-11 09:13
@gajus same as before just dont use spread with query
