### ISSUE TITLE
Unhelpful error message "Error: [object Object]"

### ISSUE THREAD

**Issue by mheitzibm** [petkaantonov/bluebird#761] opened 2015-09-11 17:15 UTC
I got an Error thrown from ensureErrorObject in util.js whose message is simply "Error: [object Object]".  That doesn't tell me anything about my problem.  Please do JSON.stringify instead.

**Comment by benjamingr** [comment] 2015-09-11 17:36
Thanks for the feedback, care to add a reproducing PR?

**Comment by benjamingr** [comment] 2015-09-11 17:37
Reproducing sample I mean, so we can make a PR

**Comment by mheitzibm** [comment] 2015-09-14 13:02
Sure, I'll see what I can come up with.

**Comment by AndrewHuffman** [comment] 2015-09-16 01:42
@benjamingr I don't have reproduction steps for you, but I believe the problematic code is here: https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L236

Can we consider using `util.inspect` for this?

**Comment by AndrewHuffman** [comment] 2015-09-16 01:47
Forgot about browsers. `JSON.stringify` with a [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter)?

**Comment by benjamingr** [comment] 2015-09-16 05:57
We support browsers that do not have JSON.parse :D 

The issue here is objects with getters and/or proxies can cause side effects when iterated and that sounds like potentially really nasty bugs.

If the object has a constructor it'd print `[object Type]` which is better.

If you have a safe solution I'm game.

**Comment by AndrewHuffman** [comment] 2015-09-16 13:27
> The issue here is objects with getters and/or proxies can cause side effects when iterated and that sounds like potentially really nasty bugs.

[`Object.getOwnPropertyDescriptor`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor) may help with this.

**Comment by mheitzibm** [comment] 2015-09-16 13:43
Here's a snippet to reproduce this in Node.
```
var Promise = require('bluebird');

function tryIt(name, act) {
	var def = Promise.defer();
	setTimeout(function () {
		act(def);
	}, 
	1000);
	def.promise.then(function (val) {
		console.log(name + ': got result ' + val);
	}).catch(function (err) {
		console.log(name + ': got err ' + err);
	});
}

tryIt('resolve', function (def) { def.resolve('done'); });
tryIt('reject with string', function (def) { def.reject('unhappy'); });
tryIt('reject with Error', function (def) { def.reject(new Error('doom')); });
tryIt('reject with object', function (def) { def.reject({death: true}); });
```

This is the output
```
resolve: got result done
reject with string: got err unhappy
reject with Error: got err Error: doom
reject with object: got err [object Object]
```

**Comment by mheitzibm** [comment] 2015-09-16 13:48
This shows the problem in Node.
```
var Promise = require('bluebird');

var def = Promise.defer();
setTimeout(function () {
	def.reject({death: true});
}, 
1000);
def.promise.then(function (val) {
	console.log(name + ': got result ' + val);
});
```

Here's the output
```
$ node app.js
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/mheitz/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/home/mheitz/node_modules/bluebird/js/main/promise.js:469:22)
    at PromiseResolver.reject (/home/mheitz/node_modules/bluebird/js/main/promise_resolver.js:97:18)
    at null._onTimeout (/home/mheitz/repo/app.js:6:6)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by benjamingr** [comment] 2015-09-16 14:00
@mhamann oh, this is going to be an extremely hard sell then, sorry. 

The policy is that you should always reject with `Error` objects. If you reject with anything else, you don't get a stack trace and the name of the error is the least of your worries. We wrap with errors when promisifying libraries (`promisifyAll` and `promisify`).

I'm sorry, but I don't think Petka will be interested. He might reopen if he is.

**Closed by benjamingr** 2015-09-16 14:00 UTC
Labels: pending-author-input

**Comment by mheitzibm** [comment] 2015-09-16 14:02
Maybe you could test for JSON.stringify since most browsers have it.  Use it if it exists, otherwise fall back to what you do today.

**Comment by benjamingr** [comment] 2015-09-16 14:26
But there are cases this won't work (with getters/proxies) and the use case is very rare anyway since you're not throwing an error. My recommendation is that you throw `Error`s.

If you feel strongly about this, you can of course add a custom unhandled rejection handler and deal with it yourself:

```js
process.on("unhandledRejection", function(reason, promise) {
    console.log("Possibly Unhandled Rejection", JSON.stringify(reason)); 
});
```

This will cause your wanted behavior for all promises in your code.

**Comment by AndrewHuffman** [comment] 2015-09-16 14:54
@benjamingr We already have that but bluebird wraps `obj + ""` version of the object: https://github.com/petkaantonov/bluebird/blob/master/src/util.js#L263. Why can't this just simply do `new Error(obj)` ?

Also, I'm not able to enumerate `getters` when I test using `JSON.stringify`. I'm going to play around with this some more but I'm not certain that's an issue. Circular references will need to be able handled, though (or cut at a depth of 1).

**Comment by benjamingr** [comment] 2015-09-16 14:56
> Why can't this just simply do new Error(obj) ?

Because rejecting with anything other than what was provided violates the specification and makes the library ES2015 promises and Promises/A+ incompatible, basically. Assuming I understood your suggestion.

**Comment by AndrewHuffman** [comment] 2015-09-16 15:29
Gotcha

**Comment by mato75** [comment] 2016-01-11 17:31
I am getting the same error when using library with nodejs.

**Comment by stephenotalora** [comment] 2017-06-02 15:58
@benjamingr why was this closed? This issue is still happening ....
