### ISSUE TITLE
Possible memory leak with .finally()

### ISSUE THREAD

**Issue by jameshy** [petkaantonov/bluebird#1074] opened 2016-04-17 16:41 UTC
**1) What version of bluebird is the issue happening on?**

Tested with 3.3.4 and 3.3.5.

**2) What platform and version?**

Debian 8.3
Node.js v5.10.1

**3) Did this issue happen with earlier version of bluebird?**

Untested

**Description:**

Running the leaky version of the code crashes in 10 seconds with the console output:
```
<--- Last few GCs --->

   14110 ms: Scavenge 1413.9 (1458.1) -> 1413.9 (1458.1) MB, 20.8 / 0 ms (+ 3.9 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   15042 ms: Mark-sweep 1413.9 (1458.1) -> 1413.9 (1458.1) MB, 931.8 / 0 ms (+ 6.3 ms in 3 steps since start of marking, biggest step 3.9 ms) [last resort gc].
   15972 ms: Mark-sweep 1413.9 (1458.1) -> 1413.9 (1458.1) MB, 930.0 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2e2215e3ac1 <JS Object>
    1: _then [/home/james/dev/pg-job-queue/node_modules/bluebird/js/release/promise.js:~215] [pc=0x26c553fc0d30] (this=0x28c26c004141 <a Promise with map 0x3b4e5333961>,didFulfill=0x2dd567b6b161 <JS Function finallyHandler (SharedFunctionInfo 0x15ac9ad96fc1)>,didReject=0x2dd567b6b161 <JS Function finallyHandler (SharedFunctionInfo 0x15ac9ad96fc1)>,_=0x2e221504189 <undefined>,receiver=0x28c26c004...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
fish: “node test.js” terminated by signal SIGABRT (Abort)
```

This code leaks:
```javascript
'use strict'
var Promise = require('bluebird')

function infiniteLoop() {
    var loop = function() {
        return Promise.resolve().finally(function() {
            return loop()
        })
    }
    return loop()
}

infiniteLoop()
```

This code does not:
```javascript
'use strict'
var Promise = require('bluebird')

function infiniteLoop() {
    var loop = function() {
        return Promise.resolve().then(function() {
            return loop()
        })
    }
    return loop()
}

infiniteLoop()
```

**Comment by petkaantonov** [comment] 2016-04-17 17:02
Duplicate of #1009

**Closed by petkaantonov** 2016-04-17 17:02 UTC
