### ISSUE TITLE
unhandledrejection not fired after promise.bind()

### ISSUE THREAD

**Issue by fenivana** [petkaantonov/bluebird#862] opened 2015-11-10 05:44 UTC
```js
    window.addEventListener('unhandledrejection', function(event) {
      alert(event.detail.promise.reason());
    });

    Promise.reject(new Error('1')); // alert
    Promise.reject(new Error('2')).bind(window); // no alert
```

**Comment by benjamingr** [comment] 2015-11-10 08:09
Duplicate of https://github.com/petkaantonov/bluebird/issues/841 thanks for the report!

**Closed by benjamingr** 2015-11-10 08:09 UTC
Labels: 3.0.0, bug, duplicate
