### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by jcubic** [petkaantonov/bluebird#716] opened 2015-07-30 12:29 UTC
I'm using elastic search that use bluebird in node and I've got his error:

```
ReferenceError: self is not defined
    at D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\captured_trace.js:481:26
    at Function.CapturedTrace.fireRejectionEvent (D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\captured_trace.js:233:28)
    at Promise._notifyUnhandledRejection (D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\promise.js:863:23)
    at Async._drainQueue (D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\async.js:84:12)
    at Async._drainQueues (D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\async.js:91:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\home\site\wwwroot\node_modules\elasticsearch\node_modules\bluebird\js\main\async.js:14:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```
in node self is indeed undefined.

**Comment by benjamingr** [comment] 2015-07-30 13:00
@jcubic please provide a reproducing code sample if possible.

**Comment by petkaantonov** [comment] 2015-07-31 06:17
This code path is not executed in node

**Comment by phpnode** [comment] 2015-07-31 08:58
Possibly the browser build getting included for some reason?

**Comment by GerHobbelt** [comment] 2015-10-04 21:38
One example where this fails is where bluebird is used in jsdoc.

How to reproduce:

- git clone jsdoc from github
- rm -rf node_modules/ 
(they have a package.json *and* meanwhile have a lot of the very same node_modules/ stuff also checked into their own repo  :-1:  )
- npm install
- npm update
(or any other means to get the latest bluebird in there)
- gulp
(kaboom! Error in bluebird at the reported location by the OP)


And otherwise a simple code review of the given file (captured_trace.js) function `fireGlobalEvent` should immediately pop this one up; 

Also: run it through any linter and you get warned immediately.

Three ways to get this one.

Quick hack to 'fix' this one -- at least to shut bluebird code up: add this line of code

```
    var self = this;
```

immediately after the start of the declaration of said function, so that it will then look like this:

```
var fireGlobalEvent = (function() {
    var self = this;
    if (util.isNode) {
        return function(name, reason, promise) {
...
```

**Comment by petkaantonov** [comment] 2015-10-27 16:37
Due to strict mode and CSP it's not possible to get reference to the global object without hard coding it like `self`. `var self = this` fails in strict mode.

**Comment by benjamingr** [comment] 2015-12-06 19:11
Where is this standing?

**Comment by benjamingr** [comment] 2015-12-16 11:54
Freezing for inactivity.

**Closed by benjamingr** 2015-12-16 11:54 UTC
Labels: pending-author-input
