### ISSUE TITLE
Runaway promise warning lacks long stack trace when using chained fromCallback() calls

### ISSUE THREAD

**Issue by ben-page** [petkaantonov/bluebird#971] opened 2016-01-22 21:26 UTC
I found a case where the runaway promise warning does not include the long stack trace.
```javascript
var Promise = require('bluebird');
Promise.config({warnings: true, longStackTraces: true});

function fn(cb) {
    setTimeout(cb.bind(null, null, 'result'), 0);
}

Promise.fromCallback(function (callback) {
    fn(callback);
})
.then(function (t) {
    Promise.fromCallback(function (callback) { //runaway promise
        fn(callback);
    });
});
```

```
Warning: a promise was created in a handler but was not returned from it
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by ben-page** [comment] 2016-01-22 21:27
I'm on 3.1.1

**Comment by petkaantonov** [comment] 2016-01-22 21:39
Duplicate of #9

**Comment by ben-page** [comment] 2016-01-22 22:40
@petkaantonov I don't think this duplicate of the issue #9. The issue you indicated seems to be about an error throw inside asynchronous (setTimeout) code executed inside a Promise.

My issue is about the runaway Promise warning not including a long stack trace, when the inner Promise originates from fromCallback(). If it originated anywhere else, it would work. I think it may be related to #871. And I do not believe this would require domains, AsyncListener, or similar to solve.

**Comment by ben-page** [comment] 2016-01-23 01:09
To illustrate my point, here I made a custom implementation of fromCallback() based on the Promise constructor. It creates a long stack trace as expected.

```javascript
Promise.config({warnings: true, longStackTraces: true});

function fn(cb) {
    setTimeout(cb.bind(null, null, 'result'), 0);
}

function fromCallback(nodeFunction) {
    return new Promise(function(resolve, reject) {
        nodeFunction(function (err, res) {
            if (err)
                return reject(err);

            resolve(res);
        });
    });
}

fromCallback(fn)
    .then(function (t) {
        fromCallback(fn);
    });
```

**Closed** 2016-01-23 22:18 UTC
Labels: 3.0.0, bug
