### ISSUE TITLE
Promise functions run twice, depending on how chaining is performed.

### ISSUE THREAD

**Issue by pignatenko** [petkaantonov/bluebird#604] opened 2015-04-28 22:03 UTC
I first encountered this in Knex. I have a SQL query that just selects the next number from a sequence. This is basically something like  `select nextval('myseq')`. When I return the promise from the knex.raw call and I use .then and .catch I get double call behavior depending on how I attach the calls.

For example:

```
var promise = knex.raw('select....');
promise.then(myfunc);
promise.catch(handleerror);
```

This will make the select call run twice and return however if I write.

```
var promise = knex.raw('select....');
promise.then(myfunc).catch(handleerror);
```

The select call will only run once.

**Comment by bendrucker** [comment] 2015-04-28 22:18
This is not related to Bluebird. Knex queries are "thenables," meaning that they're not true promises but they return promises when their `then` methods are called (or aliases like `catch`).

Chain your method calls. Otherwise this is expected behavior. There will be a way to address this with `WeakMap`s so that your original example fires one query. Without them, providing that behavior would represent a memory leak. So for the time being and a decent while longer, you need to fix your code here.

**Comment by petkaantonov** [comment] 2015-04-29 05:41
To chain with variables you need to keep reassigning:

```js
var promise = knex.raw('select....');
promise = promise.then(myfunc);
promise = promise.catch(handleerror);
```

Promise chaining is different from jQuery chaining because everything returns a *new* promise while jQuery methods return the *same* object.

**Closed by petkaantonov** 2015-04-29 05:41 UTC
